<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from C:\xampp2\htdocs\drupal-test\sites\default\files\civicrm\ext\com.joineryhq.inventoryfield\xml/schema/CRM/Inventoryfield/Inventoryfield.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:fc8f54dcfe9fe8f92936f206469176b8)
 */
use CRM_Inventoryfield_ExtensionUtil as E;

/**
 * Database access object for the Inventoryfield entity.
 */
class CRM_Inventoryfield_DAO_Inventoryfield extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_inventoryfield';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique Inventoryfield ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to civicrm_custom_field.id
   *
   * @var int
   */
  public $custom_field_id;

  /**
   * @var int
   */
  public $limit_per;

  /**
   * @var int
   */
  public $limit_per_amount;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_inventoryfield';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Inventoryfields') : E::ts('Inventoryfield');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'custom_field_id', 'civicrm_custom_field', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique Inventoryfield ID'),
          'required' => TRUE,
          'where' => 'civicrm_inventoryfield.id',
          'table_name' => 'civicrm_inventoryfield',
          'entity' => 'Inventoryfield',
          'bao' => 'CRM_Inventoryfield_DAO_Inventoryfield',
          'localizable' => 0,
          'add' => NULL,
        ],
        'custom_field_id' => [
          'name' => 'custom_field_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to civicrm_custom_field.id'),
          'where' => 'civicrm_inventoryfield.custom_field_id',
          'table_name' => 'civicrm_inventoryfield',
          'entity' => 'Inventoryfield',
          'bao' => 'CRM_Inventoryfield_DAO_Inventoryfield',
          'localizable' => 0,
          'FKClassName' => 'CRM_Core_DAO_CustomField',
          'add' => NULL,
        ],
        'limit_per' => [
          'name' => 'limit_per',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Limit Per'),
          'where' => 'civicrm_inventoryfield.limit_per',
          'default' => '0',
          'table_name' => 'civicrm_inventoryfield',
          'entity' => 'Inventoryfield',
          'bao' => 'CRM_Inventoryfield_DAO_Inventoryfield',
          'localizable' => 0,
          'add' => NULL,
        ],
        'limit_per_amount' => [
          'name' => 'limit_per_amount',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Limit Per Amount'),
          'where' => 'civicrm_inventoryfield.limit_per_amount',
          'default' => '1',
          'table_name' => 'civicrm_inventoryfield',
          'entity' => 'Inventoryfield',
          'bao' => 'CRM_Inventoryfield_DAO_Inventoryfield',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'inventoryfield', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'inventoryfield', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
